# Generated by Django 5.0.6 on 2025-06-07 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('adjustment_type', models.CharField(choices=[('ADDBACK', 'Addback'), ('NORMALIZATION', 'Normalization'), ('DISCRETIONARY', 'Discretionary')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rationale', models.TextField()),
                ('source_reference', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('QB', 'QuickBooks'), ('PAYROLL', 'Payroll System'), ('SUPPLEMENTAL', 'Supplemental Notes')], max_length=20)),
                ('file_path', models.FileField(upload_to='data_sources/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GLDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('debit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('compensation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('benefits', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='RecastPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cogs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('operating_expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ebitda', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustments', models.ManyToManyField(to='core.adjustment')),
            ],
        ),
        migrations.CreateModel(
            name='SupplementalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('impact_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datasource')),
            ],
        ),
        migrations.AddIndex(
            model_name='adjustment',
            index=models.Index(fields=['date'], name='core_adjust_date_8b0bee_idx'),
        ),
        migrations.AddIndex(
            model_name='adjustment',
            index=models.Index(fields=['status'], name='core_adjust_status_2aa60d_idx'),
        ),
        migrations.AddIndex(
            model_name='gldetail',
            index=models.Index(fields=['date'], name='core_gldeta_date_1adfab_idx'),
        ),
        migrations.AddIndex(
            model_name='gldetail',
            index=models.Index(fields=['account_number'], name='core_gldeta_account_4e1d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['employee_name'], name='core_payrol_employe_e317b5_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['date'], name='core_payrol_date_56a3b1_idx'),
        ),
        migrations.AddIndex(
            model_name='recastpl',
            index=models.Index(fields=['date'], name='core_recast_date_17d3cc_idx'),
        ),
    ]
