# Generated by Django 4.2.7 on 2025-06-10 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GLDetail',
            new_name='QuickbookRecord',
        ),
        migrations.RenameIndex(
            model_name='quickbookrecord',
            new_name='core_quickb_date_938aa7_idx',
            old_name='core_gldeta_date_1adfab_idx',
        ),
        migrations.RenameIndex(
            model_name='quickbookrecord',
            new_name='core_quickb_account_e9322c_idx',
            old_name='core_gldeta_account_4e1d3d_idx',
        ),
    ]
