# Generated by Django 4.2.7 on 2025-06-11 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_rename_gldetail_quickbookrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('QB', 'QuickBooks'), ('PAYROLL', 'Payroll System'), ('SUPPLEMENTAL', 'Supplemental Notes'), ('STOC', 'STOC Accounting')], max_length=20),
        ),
        migrations.CreateModel(
            name='StocAccountingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('location_state', models.CharField(blank=True, max_length=100, null=True)),
                ('external_financial_statement', models.CharField(blank=True, max_length=100, null=True)),
                ('calendar_year_fiscal_year', models.CharField(blank=True, max_length=100, null=True)),
                ('stub_period', models.DateField(blank=True, null=True)),
                ('financial_reporting_period_1', models.DateField(blank=True, null=True)),
                ('financial_reporting_period_2', models.DateField(blank=True, null=True)),
                ('qe_summary_status', models.CharField(choices=[('OK', 'Ok!'), ('ERROR', 'Error!'), ('N/A', 'Not Applicable')], default='N/A', max_length=10)),
                ('recast_reported_status', models.CharField(choices=[('OK', 'Ok!'), ('ERROR', 'Error!'), ('N/A', 'Not Applicable')], default='N/A', max_length=10)),
                ('recast_mgmt_adjusted_status', models.CharField(choices=[('OK', 'Ok!'), ('ERROR', 'Error!'), ('N/A', 'Not Applicable')], default='N/A', max_length=10)),
                ('other_recast_status', models.CharField(choices=[('OK', 'Ok!'), ('ERROR', 'Error!'), ('N/A', 'Not Applicable')], default='N/A', max_length=10)),
                ('lead_profit_and_loss_status', models.CharField(choices=[('OK', 'Ok!'), ('ERROR', 'Error!'), ('N/A', 'Not Applicable')], default='N/A', max_length=10)),
                ('monthly_profit_and_loss_status', models.CharField(choices=[('OK', 'Ok!'), ('ERROR', 'Error!'), ('N/A', 'Not Applicable')], default='N/A', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'STOC Accounting Data',
                'verbose_name_plural': 'STOC Accounting Data',
            },
        ),
    ]
